# Generated by Django 5.0.7 on 2024-08-06 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='secondary_phone',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
